"""Purgatory Report Generator — markdown and JSON output."""

import json
from datetime import datetime
from pathlib import Path
from typing import Any


def generate_report(skill_path: Path, results: list[dict], score: dict, fmt: str = "markdown") -> str:
    """Generate a Purgatory vetting report."""
    if fmt == "json":
        return json.dumps({
            "skill": str(skill_path),
            "timestamp": datetime.now().isoformat(),
            "score": score,
            "layers": results,
        }, indent=2)

    # Markdown report
    lines = []
    lines.append("---")
    lines.append(f"title: Purgatory Report — {skill_path.name}")
    lines.append("type: security-report")
    lines.append(f"date: {datetime.now().strftime('%Y-%m-%d')}")
    lines.append(f"skill: {skill_path.name}")
    lines.append(f"trust_tier: {score['trust_tier']}")
    lines.append(f"trust_score: {score['trust_score']}")
    lines.append("---")
    lines.append("")
    lines.append(f"# Purgatory Report — {skill_path.name}")
    lines.append("")
    lines.append(f"**Scanned:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"**Trust Score:** {score['trust_score']}/100")
    lines.append(f"**Trust Tier:** {score['trust_tier']} — {score['tier_label']}")
    lines.append(f"**Lab Use:** {score['lab_use']}")
    lines.append(f"**Prod Use:** {score['prod_use']}")
    lines.append("")

    if score["hard_fails"]:
        lines.append("## Hard Fails")
        for fail in score["hard_fails"]:
            lines.append(f"- {fail}")
        lines.append("")

    if score["warnings"]:
        lines.append("## Warnings")
        for warn in score["warnings"]:
            lines.append(f"- {warn}")
        lines.append("")

    lines.append("## Layer Scores")
    lines.append("")
    lines.append("| Layer | Score |")
    lines.append("|---|---|")
    for layer, lscore in score["layer_scores"].items():
        lines.append(f"| {layer} | {lscore}/100 |")
    lines.append("")

    lines.append("## Controls Required")
    lines.append("")
    lines.append(f"- Sandbox: {'Required' if score['required_sandbox'] else 'Optional'}")
    lines.append(f"- Secret Isolation: {'Required' if score['required_secret_isolation'] else 'Optional'}")
    lines.append(f"- Manual Review: {'Required' if score['required_manual_review'] else 'Optional'}")
    lines.append("")

    # Detailed findings per layer
    for result in results:
        layer = result.get("layer", "unknown")
        findings = result.get("findings", [])

        if findings:
            lines.append(f"## Layer: {layer}")
            lines.append("")
            lines.append(f"| Severity | Type | File | Detail |")
            lines.append("|---|---|---|---|")
            for f in findings[:20]:  # Cap at 20 per layer
                file_short = Path(f.get("file", "")).name
                lines.append(f"| {f['severity']} | {f['type']} | {file_short}:{f.get('line', 0)} | {f['detail']} |")
            lines.append("")

    lines.append("---")
    lines.append("*Generated by Purgatory v0.1.0*")

    return "\n".join(lines)
